# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d0d893c921cc15d83182ffb0cd3f9a4793ca69ad21bfc1abc148d9a0382461209a3c4d030da245914883fd31e8fd8dbc28afc16f53ae419c9d829966050637fc

test:
  secret_key_base: 36f8a84f42e1be8de214340b259a257363854188cb4de005cd9052319d018ca528b4b81b8427e1d6e1046490b1afa73adaa4fbe6d0b65be2e48f28b77073ad7c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
