Category.create(name: 'Upper Body')
Category.create(name: 'Lower Body')
Category.create(name: 'Total Body')
Category.create(name: 'Abs')

TrainingType.create(name: 'Strength Training')
TrainingType.create(name: 'Pilates')
TrainingType.create(name: 'Cardio')
TrainingType.create(name: 'Yoga')
TrainingType.create(name: 'Impact')
TrainingType.create(name: 'Kickboxing')

Equipment.create(name: 'Dumbbells')
Equipment.create(name: 'Medicine ball')
Equipment.create(name: 'Yoga Mat')
Equipment.create(name: 'Jump Rope')
Equipment.create(name: 'Yoga Ball')
Equipment.create(name: 'Resistance Bands')
